version: "3"

services:
  petfinder-graphql:
    image: wbw4sv/petfinder-graphql
    container_name: petfinder-graphql
    ports:
      - 4000:4000
    restart: always
    environment:
      - PETFINDER_API_KEY=${PETFINDER_API_KEY}
      - PETFINDER_SECRET_KEY=${PETFINDER_SECRET_KEY}
      - THE_DOG_API_KEY=${THE_DOG_API_KEY}
      - NODE_ENV=production

  petfinder-reverse-proxy:
    image: nginx
    container_name: petfinder-reverse-proxy
    volumes:
      - ./petfinder-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./petfinder-reverse-proxy/ssl:/ssl/
    ports:
      - 80:80
      - 443:443
    restart: always

  webapp:
    build: ./webapp
    container_name: petfinder-frontend
    ports:
      - 3000:3000
    restart: always
    environment:
      - GRAPHQL_URL=http://petfinder-graphql:4000/graphql
      - NODE_ENV=production
